#服务配置
server:
  port: 8022 #[localhost]

#spring配置
spring:
  datasource:
    username: tester #[localhost]
    password: tester #[localhost]
    url: jdbc:mysql://localhost:3306/wusthelper?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


