#mybatis config
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.linghang.skimlessons
  configuration:
    map-underscore-to-camel-case: true

#page helper config
pagehelper:
  helperDialect: mysql
  reasonable: false #[true]When pageNum out of bounds, keep returning data

#log config
logging:
  level:
    com.linghang.skimlessons.dao: debug
  config: classpath:conf/logback-spring.xml

spring:
  profiles:
    active: dev
